# Generated by Django 3.0.6 on 2020-05-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='file',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='texp',
        ),
        migrations.AddField(
            model_name='trainer',
            name='q_s',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='trainer',
            name='texp1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='trainer',
            name='texp2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='trainer',
            name='turl',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='tprofile',
            field=models.FileField(default='', upload_to='facilitators/profile'),
        ),
    ]
