# Generated by Django 3.0.6 on 2020-05-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('Signup_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=100)),
                ('Poi', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='', upload_to='Trainer/images'),
        ),
    ]
