# Generated by Django 3.0.6 on 2020-05-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0002_auto_20200530_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
