# Generated by Django 3.0.6 on 2020-06-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0003_auto_20200530_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCounselling',
            fields=[
                ('OC_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
