# Generated by Django 3.0.7 on 2020-07-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('Eid', models.AutoField(primary_key=True, serialize=False)),
                ('Linkedin_Url', models.URLField(max_length=250)),
                ('Website_Url', models.URLField(max_length=250)),
                ('Youtube_Url', models.URLField(max_length=250)),
                ('RExperience', models.CharField(choices=[('', 'Relative Experience'), ('A', '3-6 yrs'), ('B', '6-10 yrs'), ('C', '10+ yrs')], max_length=1)),
                ('TExperience', models.CharField(choices=[('', 'Total Experience'), ('A', '3-6 yrs'), ('B', '6-10 yrs'), ('C', '10+ yrs')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FacilitatorQueries',
            fields=[
                ('Qid', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Resolved', 'Resolved'), ('Doubt', 'Doubt')], default='Doubt', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=30)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Learner'), (2, 'Facilitator'), (3, 'Admin')], null=True)),
                ('phone', models.CharField(max_length=13)),
                ('portfolio', models.FileField(upload_to='uploads/')),
                ('profile', models.ImageField(default='default.png', upload_to='Mentor_profiles/')),
                ('intrest', models.CharField(max_length=250)),
            ],
        ),
    ]
