# Generated by Django 3.0.7 on 2020-07-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0002_auto_20200714_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
