# Generated by Django 3.0.7 on 2020-07-16 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilitators', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('Fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('PAddress', models.TextField(blank=True, null=True)),
                ('TAddress', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
