# Generated by Django 3.0.7 on 2020-06-30 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilitators', '0003_auto_20200601_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('Eid', models.AutoField(primary_key=True, serialize=False)),
                ('Linkedin_Url', models.URLField(max_length=250)),
                ('Website_Url', models.URLField(max_length=250)),
                ('Youtube_Url', models.URLField(max_length=250)),
                ('RExperience', models.TextField()),
                ('TExperience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('Fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('phone', models.CharField(max_length=13)),
                ('PAddress', models.TextField(null=True)),
                ('TAddress', models.TextField(blank=True, null=True)),
                ('profile', models.ImageField(upload_to='Mentor_profiles/% Y/% m/% d/')),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilitatorQueries',
            fields=[
                ('Qid', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('R', 'Resolved'), ('D', 'Doubt')], default='Doubt', max_length=1)),
                ('Fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilitators.Facilitator')),
            ],
        ),
        migrations.CreateModel(
            name='FacilitatorQueriesAnswer',
            fields=[
                ('Aid', models.AutoField(primary_key=True, serialize=False)),
                ('Answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('R', 'Resolved'), ('D', 'Doubt')], default=None, max_length=1)),
                ('Qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilitators.FacilitatorQueries')),
            ],
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilitators.Course')),
                ('Fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilitators.Facilitator')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilitators.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.AddField(
            model_name='experience',
            name='Fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilitators.Facilitator', unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subCat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilitators.SubCategory'),
        ),
    ]
