# Generated by Django 3.0.7 on 2020-07-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0004_auto_20200630_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='portfolio',
            field=models.FileField(default=1, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='PAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='profile',
            field=models.ImageField(default='default.png', upload_to='Mentor_profiles/% Y/% m/% d/'),
        ),
    ]
