# Generated by Django 3.0.7 on 2020-07-03 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilitators', '0005_auto_20200702_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='Fid',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='Uid',
        ),
        migrations.AddField(
            model_name='experience',
            name='facilitator',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='facilitators.Facilitator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilitator',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
