# Generated by Django 3.0.7 on 2020-07-03 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilitators', '0007_auto_20200703_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=30)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Learner'), (2, 'Facilitator'), (3, 'Admin')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='subCat_id',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='facilitatorqueries',
            name='Fid',
        ),
        migrations.RemoveField(
            model_name='facilitatorqueriesanswer',
            name='Qid',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='Cid',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='Fid',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='cat_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Facilitator',
        ),
        migrations.DeleteModel(
            name='FacilitatorQueries',
        ),
        migrations.DeleteModel(
            name='FacilitatorQueriesAnswer',
        ),
        migrations.DeleteModel(
            name='offer',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
