# Generated by Django 3.0.7 on 2020-07-03 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilitators', '0008_auto_20200704_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.FileField(default=1, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='default.png', upload_to='Mentor_profiles/% Y/% m/% d/'),
        ),
        migrations.CreateModel(
            name='FacilitatorQueries',
            fields=[
                ('Qid', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('R', 'Resolved'), ('D', 'Doubt')], default='Doubt', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('Eid', models.AutoField(primary_key=True, serialize=False)),
                ('Linkedin_Url', models.URLField(max_length=250)),
                ('Website_Url', models.URLField(max_length=250)),
                ('Youtube_Url', models.URLField(max_length=250)),
                ('RExperience', models.TextField()),
                ('TExperience', models.TextField()),
                ('facilitator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
