# Generated by Django 3.0.7 on 2020-07-05 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilitators', '0014_auto_20200705_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitatorqueries',
            name='status',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Doubt', 'Doubt')], default='Doubt', max_length=10),
        ),
        migrations.AlterField(
            model_name='facilitatorqueries',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
