# Generated by Django 3.0.7 on 2020-07-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0015_auto_20200705_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='portfolio',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='default.png', upload_to='Mentor_profiles/'),
        ),
    ]
