# Generated by Django 3.0.7 on 2020-07-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0016_auto_20200705_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intrest',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
