# Generated by Django 3.0.7 on 2020-07-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0017_profile_intrest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='RExperience',
            field=models.CharField(choices=[('', 'Relative Experience'), ('A', '3-6 yrs'), ('B', '6-10 yrs'), ('C', '10+ yrs')], max_length=1),
        ),
        migrations.AlterField(
            model_name='experience',
            name='TExperience',
            field=models.CharField(choices=[('', 'Total Experience'), ('A', '3-6 yrs'), ('B', '6-10 yrs'), ('C', '10+ yrs')], max_length=1),
        ),
    ]
